citation:

  # engine for citation generation
  # possible values are 'csl' or 'none'
  engine: csl

  # example 'csl' style citation generation
  # see: https://github.com/LibreCat/LibreCat/wiki/Citation-Style-Language
  csl:
    url: 'http://localhost:8085'
    default_style: short
    styles:
      apa: apa
      ama: american-medical-association
      chicago: chicago-fullnote-bibliography
      ieee: ieee
      mla: modern-language-association
      short: elsevier-without-titles

store:
  main:
    options:
      bags:
        citation:
          plugins: ['Datestamps']

route:
  exporter:
    publication:
      docx:
        package: Citation
        content_type: 'application/vnd.openxmlformats-officedocument.wordprocessingml.document'
        options:
          fix: ["nothing()"]
          extension: docx
          label: DOCX
          format: docx
          name: LibreCat
          host: http://librecat.org
      odt:
        package: Citation
        content_type: 'application/vnd.oasis.opendocument.text'
        options:
          fix: ["nothing()"]
          extension: odt
          label: ODT
          format: odt
          name: LibreCat
          host: http://librecat.org
